# Author: James Ashmore
# Copyright: Copyright 2020, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

rule all:
    input:
        "analysis/01-quality-control/TENxPBMCData.rds"

# Workflow rules
include: "rules/01-quality-control.smk"