# Author: James Ashmore
# Copyright: Copyright 2020, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

rule all:
    input:
        "analysis/01-quality-control/barcodeRanks.csv",
        "analysis/01-quality-control/barcodeRanks1.pdf",
        "analysis/01-quality-control/emptyDrops.csv",
        "analysis/01-quality-control/emptyDrops1.pdf",
        "analysis/01-quality-control/emptyDrops2.pdf",
        "analysis/01-quality-control/emptyDrops3.pdf",
        "analysis/01-quality-control/filterDrops.rds",
        "analysis/01-quality-control/perCellQCMetrics.csv",
        "analysis/01-quality-control/plotCellSum.pdf",
        "analysis/01-quality-control/plotCellDetected.pdf",
        "analysis/01-quality-control/manualPerCellQC.csv",
        "analysis/01-quality-control/quickPerCellQC.csv",
        "analysis/01-quality-control/robustPerCellQC.csv",
        "analysis/01-quality-control/eulerPerCellQC.pdf",
        "analysis/01-quality-control/topTagsByQC.csv",
        "analysis/01-quality-control/plotTagsByQC.pdf",
        "analysis/01-quality-control/filterCellByQC.rds",
        "analysis/01-quality-control/perFeatureQCMetrics.csv",
        "analysis/01-quality-control/plotFeatureMean.pdf",
        "analysis/01-quality-control/plotFeatureDetected.pdf",
        "analysis/01-quality-control/plotFeatureExprs.pdf",
        "analysis/01-quality-control/plotHighestExprs.pdf",
        "analysis/01-quality-control/plot1.pdf",
        "analysis/01-quality-control/calculatePCA.csv",
        "analysis/01-quality-control/calculateTSNE.csv",
        "analysis/01-quality-control/calculateUMAP.csv",
        "analysis/01-quality-control/plotPCA.sum.pdf",
        "analysis/01-quality-control/plotPCA.detected.pdf",
        "analysis/01-quality-control/plotTSNE.sum.pdf",
        "analysis/01-quality-control/plotTSNE.detected.pdf",
        "analysis/01-quality-control/plotUMAP.sum.pdf",
        "analysis/01-quality-control/plotUMAP.detected.pdf"

# Workflow rules
include: "rules/01-quality-control.smk"