name: osca
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-annotationhub
  - bioconductor-aucell
  - bioconductor-basilisk
  - bioconductor-batchelor
  - bioconductor-biocfilecache
  - bioconductor-biocneighbors
  - bioconductor-biocparallel
  - bioconductor-biocsingular
  - bioconductor-biocstyle
  - bioconductor-delayedmatrixstats
  - bioconductor-dropletutils
  - bioconductor-edger
  - bioconductor-ensdb.hsapiens.v86
  - bioconductor-go.db
  - bioconductor-gseabase
  - bioconductor-hcadata
  - bioconductor-isee
  - bioconductor-limma
  - bioconductor-mousegastrulationdata
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-pcatools
  - bioconductor-reactome.db
  - bioconductor-scater
  - bioconductor-scran
  - bioconductor-scrnaseq
  - bioconductor-singlecellexperiment
  - bioconductor-singler
  - bioconductor-slingshot
  - bioconductor-tenxbraindata
  - bioconductor-tenxpbmcdata
  - bioconductor-tradeseq
  - r-cluster
  - r-dendextend
  - r-dynamictreecut
  - r-ggbeeswarm
  - r-gridextra
  - r-igraph
  - r-knitr
  - r-matrix
  - r-msigdbr
  - r-pheatmap
  - r-rmtstat
  - r-robustbase
  - r-rtsne
  - r-statmod
  - r-uwot
  - r-viridis
  - snakemake
