# Configuration# Author: James Ashmore
# Copyright: Copyright 1010, James Ashmore
# Email: jashmore@ed.ac.uk
# License: MIT

#
#
input: pbmc4k.rds

#
#
tximeta:
  # Source (e.g. "Ensembl")
  source: "Ensembl"
  # Organism (e.g. "Homo sapiens")
  organism: "Homo sapiens"
  # Release (e.g. "27")
  release: "27"
  # Genome (e.g. "GRCh38")
  genome: "GRCh38"


# Droplet processing

DropletUtils:
  barcodeRanks:
    lower: 100
  emptyDrops:
    lower: 100
    niters: 1000
    FDR: 0.01

# Quality Control

scuttle:
  quickPerCellQC:
    nmads: 3

logNormCounts:
  downsamples: false


# Feature selection

getTopHVGs:
  fdr.threshold: 0.1

# Dimensionality reduction

calculatePCA:
  ncomponents: 50

calculateTSNE:
  perplexity: 30
  max_iter: 2500

calculateUMAP:
  n_neighbors: 15
  min_dist: 0.5

parallelUMAP:
  n_neighbors: [3, 5, 15, 30, 50, 100]
  min_dist: [0, 0.01, 0.05, 0.1, 0.5, 1]

parallelTSNE:
  perplexity: [3, 5, 15, 30, 50, 100]
  max_iter: [500, 1000, 1500, 2000, 2500, 3000]

# Clustering



# Cell cycle

cyclone:
  pairs: "human_cycle_markers.rds"


# Doublet detection

findDoubletClusters:
  nmads: 5


# Stripped detection

findStrippedClusters:
  nmads: 3

# Cell cycle assignment

# Marker gene detection
  
goana:
  species: "Hs"