# Alternative experiments (e.g. ERCC spike-in transcripts)
altexps: None

# Feature subsets (e.g. mitochondrial genes)
subsets: MT

# Quality control

# Dimensionality reduction

calculatePCA:
  - ncomponents: 50

calculateTSNE:
  - perplexity: 30
  - max_iter: 1000

calculateUMAP:
  - n_neighbors: 15
  - min_dist: 0.01
