# Alternative experiments (e.g. ERCC spike-in transcripts)
#altexps: None

# Feature subsets (e.g. mitochondrial genes)
#subsets: MT

# Quality control

# Normalization

# Feature selection

# Dimensionality reduction

# Clustering

# Marker gene detection

# Cell type annotation

# Doublet detection

# Cell cycle assignment

# Trajectory analysis