# Alternative experiments (e.g. ERCC spike-in transcripts)

# Feature subsets (e.g. mitochondrial genes)

# Quality control

# Normalization

# Feature selection

# Dimensionality reduction

# Clustering

# Marker gene detection

# Cell type annotation

# Doublet detection

# Cell cycle assignment

# Trajectory analysis